# snakemake settings
"seed": 12345
"replicates": 3
"output_dir": "results"

# species-specific settings
"species": "PhoSin"
"demo_models": [
    {"id":"Constant", 
    "num_samples_per_population": [100],
    },
    {"id":"Vaquita2Epoch_1R22",
    "num_samples_per_population": 3*[100],
    }
]
"genetic_map": null
"chrm_list": "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21"
"dfe_list": ["none", "Gamma_R22"]
"annotation_list": ["all_sites", "Phocoena_sinus.mPhoSin1.pri.110_exons"]
"mask_file": "workflows/masks/PhoSin_fake.mask.bed"
"stairway_annot_mask" : "" # set this or any of the below to 'none' to skip annot masking
"msmc_annot_mask" : ""
"gone_annot_mask" : ""
"smcpp_annot_mask" : ""

# slim settings
"slim_scaling_factor": 1
"slim_burn_in": 10

# n(t) specific configs
"methods" : ["stairwayplot", "gone", "smcpp", "msmc"]
"num_sampled_genomes_msmc" : [6]
"num_msmc_iterations" : 20
"gone_phase" : 1  # 0 for pseudohaploid, 1 for phased, 2 for unknown phase
"gone_max_snps" : 50000  # default=50000
"gone_threads" : 8
"gone_num_gens" : 2000  # default=2000
"gone_num_bins" : 400  # default=400


# exe paths
"poly_dfe_exec": "ext/polyDFE/polyDFE-2.0-linux-64-bit"
"dfe_alpha_exec": "ext/dfe-alpha-release-2.16/est_dfe"
"dfe_alpha_data_path_1": "ext/dfe-alpha-release-2.16/data"
"dfe_alpha_data_path_2": "three-epoch"
"grapes_exec": "ext/grapes/multi_grapes"
"msmc_exec" : "ext/msmc2/build/release/msmc2"
"stairwayplot_code" : "ext/stairwayplot/swarmops.jar"
"gone_code" : "ext/GONE/Linux"
