cluster:
        mkdir -p logs/{rule} &&
        sbatch
                --partition=kern,kerngpu,memory,memorylong,compute,computelong,preempt
                --account=kernlab
                --cpus-per-task={threads}
                --mem={resources.mem_mb}
                --time={resources.time}
                --job-name=smk-{rule}%j
                --output=logs/{rule}/{rule}%j.out
                --parsable
default-resources:
        - time=60
        - mem_mb=12000
        - threads=1
cluster-status: "status-sacct.sh" 
restart-times: 3
max-jobs-per-second: 1000
max-status-checks-per-second: 1000
jobs: 2000
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
jobscript: "jobscript-wo-properties.sh"
