"seed": 12345
"population_id": 0
"num_samples_per_population": [100, 100, 100]
"replicates": 2
"species": "HomSap"
"demo_models": ["OutOfAfrica_3G09"]
"annotation_id": "ensembl_havana_104_exons,exons"
"genetic_map": "HapmapII_GRCh37"
"chrm_list": "chr21"
"dfe_list": ["Gamma_H17"]
"output_dir": "results"
"poly_dfe_exec": "../ext/polyDFE/polyDFE-2.0-linux-64-bit"
